### ISSUE TITLE
Develop CDROM inventory

### ISSUE THREAD

**Issue by elawsgh** [NASA-PDS/cdrom-migration#1]
Create an inventory of all CDROMs. For each CDROM, show status indicating:
1. Data already online, where it is, CDROM can be discarded, already in the discard pile.
2. Data already online, where it is, CDROM needs to be moved to the discard pile.
3. Duplicate copy, can be discarded, CDROM already in the discard pile.
4. Duplicate copy, can be discarded, CDROM needs to be moved to the discard pile.
5. Data yet to be loaded online, where it will be uploaded

**Comment by jordanpadams** [comment]
@elawsgh do we have a status on this item?

**Comment by jordanpadams** [comment]
@elawsgh do we have a status on this or #2 ?

**Comment by jordanpadams** [comment]
This is being worked by @CSeyb with a separate task plan. Closing this and this repo.
